name: Deploy

on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    publish:
        name: Publish

        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: retypeapp/action-build@latest
              env:
                RETYPE_KEY: ${{ secrets.RETYPE_KEY }}

            - uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 7.0.x

            - uses: retypeapp/action-build@latest

            - uses: retypeapp/action-github-pages@latest
              with:
                  update-branch: true
